apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: basic-ingress
spec:
  rules:
  - http: 
      paths:
      - path: /apple
        backend:
          service:
            name: appleappservice
            port:
              number: 8080
      - path: /cat
        backend:
          service:
            name: catappservice
            port:
              number: 8080